package ship.f.engine.shared.zone

import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import ship.f.engine.shared.core.ScopedEvent
import ship.f.engine.shared.core.ScopedEvent.*
import ship.f.engine.shared.core.ScopedEvent.ViewRequest6.InitiatedViewRequest6
import ship.f.engine.shared.sdui2.SDUIInput2
import ship.f.engine.shared.utils.serverdrivenui2.config.state.models.Id2
import ship.f.engine.shared.utils.serverdrivenui2.ext.sduiLog
import ship.f.engine.shared.utils.serverdrivenui2.state.RefState2
import ship.f.engine.shared.zone.Zone2.SduiDomain.*
import kotlin.reflect.KClass

@Suppress("UNCHECKED_CAST")
abstract class Zone2<D : DomainEvent6>(val update: KClass<D>) {
    abstract val name: String
    lateinit var publish: (DomainEvent6) -> Unit
    lateinit var send: (ComputedSduiDomain<*>, String) -> Unit
    var children = listOf<String>()

    val sduiDomains = mutableMapOf<String, SduiDomain<D>>()
    val sduiDomainMutex = Mutex()

    /**
     * Called by the zone when the backing domain object is updated
     */
    abstract suspend fun create(update: D, requesterId: String): SDUIInput2

    /**
     * Called by the zone after create has either been ran or skipped
     */
    abstract suspend fun update(input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D): SDUIInput2

    /**
     * moving away from a hash based system to an input based system to enable easier flow of data
     */
    abstract fun initiateInput(input: UninitiatedViewRequest6): TrivialViewRequest6

    /**
     * requestDomain
     */
    abstract fun requestDomain(input: DomainViewRequest6): DomainEvent6

    suspend fun request3(input: ViewRequest6): List<RefState2> {
        val refs = input.id.scopes.map { RefState2(id = Id2.StateId2(name = input.id.name, scope = it, isGlobal = true)) }
        val initialisedInput = when (input) {
            is UninitiatedViewRequest6 -> {
                sduiLog("UninitiatedViewRequest6 $name for $input", tag = "ZoneGraph2 > request3")
                val initiatedInput = initiateInput(input)
                if (createOrJoinRequest(initiatedInput, publish = send)) return refs
                else initiatedInput
            }

            is InitiatedViewRequest6 -> {
                sduiLog("InitiatedViewRequest6 $name for $input", tag = "ZoneGraph2 > request3")
                input
            }
        }
        when (initialisedInput) {
            is DomainViewRequest6 -> {
                sduiLog("DomainViewRequest6 $name for $initialisedInput", tag = "ZoneGraph2 > request3")
                val sduiDomain = sduiDomainMutex.withLock {
                    sduiDomains[initialisedInput.focusDomainId] as? ComputedSduiDomain<D>
                        ?: error("sduiDomain ${initialisedInput.focusDomainId} should exist for $initialisedInput")
                }
                val updatedSduiDomain = sduiDomain.copy(
                    sdui = update(input = initialisedInput, sduiDomain.sdui, sduiDomain.domain)
                )
                addOutput(requestId = initialisedInput.requestId, domainSdui = updatedSduiDomain, publish = send)
            }

            is TrivialViewRequest6 -> {
                initialisedInput.id.scopes.forEach {
                    val domainInput = DomainViewRequest6(
                        id = Id2.ZoneId2(
                            name = initialisedInput.id.name,
                            scopes = listOf(it),
                            isAutoGenerated = initialisedInput.id.isAutoGenerated
                        ),
                        ctx = initialisedInput.ctx,
                        listCtx = initialisedInput.listCtx,
                        requesterId = initialisedInput.requesterId,
                        requestId = initialisedInput.requestId,
                        focusDomainId = it
                    )

                    when (val sduiDomain = sduiDomainMutex.withLock { sduiDomains[it] }) {
                        is ComputedSduiDomain<D> -> request3(domainInput)
                        is FailedSduiDomain<D> -> Unit // For now do nothing
                        is PendingSduiDomain<D> -> sduiDomainMutex.withLock {
                            sduiDomains[it] = sduiDomain.copy(requesters = sduiDomain.requesters + initialisedInput.requesterId)
                        }

                        null -> {
                            if (update == StaticVoid6::class) {
                                val domain = StaticVoid6(domainInput) as D
                                sduiDomainMutex.withLock {
                                    sduiDomains[it] = ComputedSduiDomain(
                                        domain = domain,
                                        sdui = create(domain, initialisedInput.requesterId),
                                        domainId = it,
                                    )
                                }
                                request3(domainInput)
                            } else {
                                val pending = PendingSduiDomain<D>(domainId = it, setOf(initialisedInput.requesterId))
                                sduiDomainMutex.withLock { sduiDomains[it] = pending }
                                publish(requestDomain(domainInput))
                            }
                        }
                    }
                }
            }
        }
        return refs
    }

    /**
     * Augment Request will finally send the sduis when the entire list is complete
     */
    suspend fun augmentRequest(input: DomainViewRequest6, domain: DomainEvent6) {
        sduiLog("Augmenting request for $input with ${domain::class}", tag = "ZoneGraph2 > augmentRequest")
        val sdui = create(domain as D, input.requestId)
        val pendingDomain = sduiDomains[domain.domainId] as? PendingSduiDomain<D> ?: error("pending should exist for $domain")
        val sduiDomain = ComputedSduiDomain(domain, sdui, domain.domainId)
        sduiDomains[domain.domainId] = sduiDomain
        pendingDomain.requesters.forEach {
            request3(input.copy(requesterId = it))
        }
    }

    fun failedDomainRequest(input: DomainViewRequest6, domainId: String) {
        val pendingDomain = sduiDomains[domainId] as? PendingSduiDomain<D> ?: return
        sduiDomains[domainId] = FailedSduiDomain(domainId = pendingDomain.domainId, requesters = pendingDomain.requesters)
//        request3(input)
    }

    sealed class SduiDomain<D : ScopedEvent> {
        abstract val domainId: String

        data class PendingSduiDomain<D : ScopedEvent>(
            override val domainId: String,
            val requesters: Set<String>,
        ) : SduiDomain<D>()

        data class ComputedSduiDomain<D : ScopedEvent>(
            val domain: D,
            val sdui: SDUIInput2,
            override val domainId: String,
        ) : SduiDomain<D>()

        data class FailedSduiDomain<D : ScopedEvent>(
            override val domainId: String,
            val requesters: Set<String>,
        ) : SduiDomain<D>()
    }

    /**
     * In theory this could be a perfect way to register a streaming interest in requests that update
     * Need sessionDependency send to indicate if sending was successful or not so we can remove from pendingRequests
     */

    companion object {
        fun <D : DomainEvent6> create(
            updateType: KClass<D>,
            name: String,
            create: suspend (update: D, requesterId: String) -> SDUIInput2,
            update: suspend ((input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D) -> SDUIInput2) = { _, sduiInput2, _ -> sduiInput2 },
            initiateInput: (input: UninitiatedViewRequest6) -> TrivialViewRequest6 = { input ->
                val id = input.id.name + input.id.scope
                TrivialViewRequest6(
                    id = input.id,
                    ctx = input.ctx,
                    listCtx = input.listCtx,
                    requesterId = input.requesterId,
                    requestId = id,
                )
            },
            requestDomain: (input: DomainViewRequest6) -> DomainEvent6 = { error("Not implemented requestDomain for $name") },
        ) = object : Zone2<D>(updateType) {
            override val name = name
            override suspend fun create(update: D, requesterId: String) = create(update, requesterId)
            override suspend fun update(input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D) =
                update(input, sduiInput2, domain)

            override fun requestDomain(input: DomainViewRequest6): DomainEvent6 = requestDomain(input)

            override fun initiateInput(input: UninitiatedViewRequest6) = initiateInput(input)
        }

        val requestBuilderMutex = Mutex()
        val requestBuilders = mutableMapOf<String, RequestBuilder>()
        lateinit var internalZoneMap: Map<String, Zone2<out DomainEvent6>> // TODO make this be the source of truth and not direct state

        suspend fun createOrJoinRequest(input: InitiatedViewRequest6, publish: suspend (ComputedSduiDomain<*>, String) -> Unit): Boolean {
            requestBuilderMutex.withLock {
                val isExistingRequest = requestBuilders[input.requestId] != null
                if (isExistingRequest) {
                    sduiLog("Joining request $input", tag = "ZoneGraph2 > createOrJoinRequest > join")
                    addRequester(input.requestId, input.requesterId, publish)
                } else {
                    sduiLog("Creating request $input", tag = "ZoneGraph2 > createOrJoinRequest > create")
                    requestBuilders[input.requestId] = RequestBuilder(
                        rootRequest = input,
                        requesters = setOf(input.requesterId),
                        output = listOf()
                    )
                }
                return isExistingRequest
            }
        }

        suspend fun addOutput(
            requestId: String,
            domainSdui: ComputedSduiDomain<*>,
            publish: suspend (ComputedSduiDomain<*>, String) -> Unit
        ) {
            requestBuilderMutex.withLock {
                val requestBuilder = requestBuilders[requestId] ?: error("No request builder for $requestId")
                requestBuilders[requestId] =
                    requestBuilder.copy(output = (requestBuilder.output + domainSdui).distinct()) // TODO is an inefficiency
                requestBuilder.requesters.forEach { publish(domainSdui, it) }
            }
        }

        suspend fun addRequester(requestId: String, requesterId: String, publish: suspend (ComputedSduiDomain<*>, String) -> Unit) {
            val requestBuilder = requestBuilders[requestId] ?: error("No request builder for $requestId")
            requestBuilders[requestId] = requestBuilder.copy(requesters = requestBuilder.requesters + requesterId)
            requestBuilder.output.forEach { publish(it, requesterId) }
        }

        data class RequestBuilder(
            val rootRequest: InitiatedViewRequest6,
            val requesters: Set<String>,
            val output: List<ComputedSduiDomain<*>>,
        )
    }
}