package ship.f.engine.shared.zone

import ship.f.engine.shared.core.ScopedEvent
import ship.f.engine.shared.core.ScopedEvent.*
import ship.f.engine.shared.core.ScopedEvent.StaticVoid6.Companion.toComputingViewRequest6
import ship.f.engine.shared.core.ScopedEvent.ViewRequest6.InitiatedViewRequest6
import ship.f.engine.shared.sdui2.SDUIInput2
import ship.f.engine.shared.utils.serverdrivenui2.config.state.models.Id2
import ship.f.engine.shared.utils.serverdrivenui2.ext.sduiLog
import ship.f.engine.shared.utils.serverdrivenui2.state.RefState2
import ship.f.engine.shared.zone.Zone.RequestResult.Success
import ship.f.engine.shared.zone.Zone.SduiDomain.*
import kotlin.reflect.KClass

@Suppress("UNCHECKED_CAST")
abstract class Zone<D : DomainEvent6>(val update: KClass<D>) {
    abstract val name: String
    lateinit var send2: (sduis: List<ComputedSduiDomain<*>>, List<String>, ViewRequest6) -> Unit
    lateinit var send3: (requestId: String) -> Unit
    lateinit var send4: (requestId: String, requesterId: String) -> Unit
    lateinit var publish: (DomainEvent6) -> Unit
    var children = listOf<String>()

    var counter = 0

    /**
     * Called by the zone when the backing domain object is updated
     */
    abstract fun create(update: D, requestId: String): SDUIInput2

    /**
     * Called by the zone after create has either been ran or skipped
     */
    abstract fun update(input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D): SDUIInput2

    /**
     * moving away from a hash based system to an input based system to enable easier flow of data
     */
    abstract fun initiateInput(input: UninitiatedViewRequest6): TrivialViewRequest6

    /**
     * requestDomain
     */
    abstract fun requestDomain(input: DomainViewRequest6): DomainEvent6


    fun request2(input: ViewRequest6): List<RefState2> {
        val initialisedInput = when(input) {
            is UninitiatedViewRequest6 -> initiateInput(input)
            is InitiatedViewRequest6 -> input
        }
        val request = requestTracker[initialisedInput.requestId]

        when(request) {
            is RequestResult2.Success -> {
                sduiLog("RequestResult2.Success $name for $initialisedInput", tag = "ZoneGraph2 > request2")
                if (input !is UninitiatedViewRequest6) error("Request already completed yet $input is trying to join late")
                send4(initialisedInput.requestId, input.requesterId)
            }
            is RequestResult2.Pending -> {
                sduiLog("RequestResult2.Pending $name for $initialisedInput", tag = "ZoneGraph2 > request2")
                if (input is UninitiatedViewRequest6 && initialisedInput.requesterId !in request.requesters.values.flatten()) {
                    // TODO this path happens when another requester joins on same request, we can ignore the request itself and just join them
                    requestTracker[initialisedInput.requestId] = request.copy(
                        requesters = request.requesters + (initialisedInput.requesterId to setOf())
                    )
                    send3(initialisedInput.requestId)
                } else {
                    // TODO this path happens when a domain input is received as a cache miss happened

                    // TODO Repeated Code, though in domain requests and derivative requests
                    val cached = mutableListOf<ComputedSduiDomain<D>>()
                    val missed = mutableListOf<PendingSduiDomain<D>>()
                    for (scope in initialisedInput.id.scopes) {
                        val domainInput = DomainViewRequest6(
                            id = Id2.ZoneId2(name = initialisedInput.id.name, scopes = listOf(scope), isAutoGenerated = initialisedInput.id.isAutoGenerated),
                            ctx = initialisedInput.ctx,
                            listCtx = initialisedInput.listCtx,
                            requesterId = initialisedInput.requesterId,
                            requestId = initialisedInput.requestId,
                            focusDomainId = scope
                        )

                        when(val sduiDomain = sduiDomains[scope]) {
                            is ComputedSduiDomain<D> -> {
                                val updatedSduiDomain = sduiDomain.copy(
                                    sdui = update(input = domainInput, sduiDomain.sdui, sduiDomain.domain)
                                )
                                cached.add(updatedSduiDomain)
                            }
                            is FailedSduiDomain<D> -> Unit // TODO to avoid getting stuck in a loop for now
                            is PendingSduiDomain<D> -> missed.add(sduiDomain) // TODO if it's already pending then we don't need to do a
                            null -> {
                                if (update != StaticVoid6::class) {
                                    PendingSduiDomain<D>(domainId = scope).also {
                                        sduiDomains[scope] = it
                                        if (update != StaticVoid6::class) {
                                            val domainRequest = requestDomain(input = domainInput)
                                            publish(domainRequest)
                                        }
                                        missed.add(it)
                                    }
                                } else {
                                    val domain = StaticVoid6(domainInput) as D
                                    val sdui = create(domain, initialisedInput.requestId)
                                    val updatedSdui = update(domainInput, sdui, domain)
                                    sduiLog("StaticVoid6 $name for $initialisedInput", tag = "ZoneGraph2 > request2")
                                    val computedSduiDomain = ComputedSduiDomain(domain = domain, sdui = updatedSdui, domainId = scope)
                                    sduiDomains[scope] = computedSduiDomain
                                    cached.add(computedSduiDomain)
                                }
                            }
                        }
                    }
                    // TODO Repeated Code
                    val currentRequest = requestTracker[initialisedInput.requestId] as? RequestResult2.Pending ?: error("RequestTracker become a non pending request $initialisedInput")
                    requestTracker[initialisedInput.requestId] = currentRequest.copy(output = (currentRequest.output + cached + missed).distinct())

                    send3(initialisedInput.requestId)
                }
            }
            null -> {
                sduiLog("RequestResult2 null $name for $initialisedInput", tag = "ZoneGraph2 > request2")
                val pendingRequest = RequestResult2.Pending(
                    rootRequest = initialisedInput,
                    output = listOf(),
                    requesters = mapOf(initialisedInput.requesterId to setOf())
                )

                requestTracker[initialisedInput.requestId] = pendingRequest

                // TODO Repeated Code
                val cached = mutableListOf<ComputedSduiDomain<D>>()
                val missed = mutableListOf<PendingSduiDomain<D>>()
                for (scope in initialisedInput.id.scopes) {
                    val domainInput = DomainViewRequest6(
                        id = Id2.ZoneId2(name = initialisedInput.id.name, scopes = listOf(scope), isAutoGenerated = initialisedInput.id.isAutoGenerated),
                        ctx = initialisedInput.ctx,
                        listCtx = initialisedInput.listCtx,
                        requesterId = initialisedInput.requesterId,
                        requestId = initialisedInput.requestId,
                        focusDomainId = scope
                    )

                    when(val sduiDomain = sduiDomains[scope]) {
                        is ComputedSduiDomain<D> -> {
                            val updatedSduiDomain = sduiDomain.copy(
                                sdui = update(input = domainInput, sduiDomain.sdui, sduiDomain.domain)
                            )
                            cached.add(updatedSduiDomain)
                        }
                        is FailedSduiDomain<D> -> Unit // TODO to avoid getting stuck in a loop for now
                        is PendingSduiDomain<D> -> missed.add(sduiDomain) // TODO if it's already pending then we don't need to do anything
                        null -> if (update != StaticVoid6::class) {
                            PendingSduiDomain<D>(domainId = scope).also {
                                sduiDomains[scope] = it
                                if (update != StaticVoid6::class) {
                                    val domainRequest = requestDomain(input = domainInput)
                                    publish(domainRequest)
                                }
                                missed.add(it)
                            }
                        } else {
                            val domain = StaticVoid6(domainInput) as D
                            val sdui = create(domain, initialisedInput.requestId)
                            val updatedSdui = update(domainInput, sdui, domain)
                            val computedSduiDomain = ComputedSduiDomain(domain = domain, sdui = updatedSdui, domainId = scope)
                            sduiDomains[scope] = computedSduiDomain
                            cached.add(computedSduiDomain)
                        }
                    }
                }
                // TODO Repeated Code
                val currentRequest = requestTracker[initialisedInput.requestId] as? RequestResult2.Pending ?: error("RequestTracker become a non pending request $initialisedInput")
                requestTracker[initialisedInput.requestId] = pendingRequest.copy(output = currentRequest.output + cached + missed)

                // TODO this will handle making sure messages are not duplicated to requesters and transitioning a request to success
                send3(initialisedInput.requestId)
            }
            is RequestResult2.Failed -> TODO("Not implemented failure branch yet")
        }

        val ref = initialisedInput.id.scopes.map { RefState2(id = Id2.StateId2(name = initialisedInput.id.name, scope = it, isGlobal = true)) }

        // Request Tracker Tracks Request Ids for Requester Ids
        // Maybe we should just centralize requests?
        // This is what we should do with the internal zone map and the subscribed requests
        // We need to distinguish between the route request and the other requests
            // The currentInput should handle handled out the requests are getting centralized and if a request is a root request or not
            // Requests should just be centralized using the ids, but the subDomainCache should be local?

        // Pending
        // Computing
        // Computed

        // Inflight => killed when the request is complete, and all subscribers have received info
        // RequesterId => idMap?

        // When
            // Null
            // Computing
                // Probably needs an allZones stack that can be joined and left to know when it's complete
                // Does it actually matter?
                // Well it does matter as we need a clean way to stop sending the same requests over to a client for same initiated request
            // Completed


        // Request Half
        // Send Half

        return ref
    }

    /**
     * Called by the user as a request, if the request is a cache miss then it will be sent so the domain can update
     * 1) If requests hit the return immediately
     * 2) If requests miss but domains hits then run update
     * 3) if request and domain miss then publish the I
     */
    fun request(input: ViewRequest6): List<RefState2> {
        val currentInput = when(input) {
            is UninitiatedViewRequest6 -> initiateInput(input)
            is TrivialViewRequest6, is DomainViewRequest6 -> input
        }
        val refs = currentInput.id.scopes.map { RefState2(id = Id2.StateId2(name = currentInput.id.name, scope = it, isGlobal = true)) }

        // TODO This adds the current requester to the list of subscribers, it's not currently used
        val requesterIds = subscribedRequests[currentInput.requestId] ?: listOf()
        subscribedRequests[currentInput.requestId] = (requesterIds + currentInput.requesterId).distinct()

        when (val cachedResult = requests[currentInput.requestId]) {
            /**
             * If the request has been cached, we don't need to run update()
             * The hash should be different if update() is required to be run again
             * TODO need to augment this for late joins
             */
            is Success<*> -> {
                sduiLog("RequestResult.Success $name for $currentInput", tag = "ZoneGraph2 > request")
                send2(cachedResult.output, currentInput.id.scopes, cachedResult.input) // In the future send to all subscribedRequests

                internalZoneMap.forEach {
                    it.value.requests[currentInput.requestId]?.let { requestResult ->
                        (requestResult as? Success<*>)?.let { success ->
                            if (it.key != name && children.contains(it.key)) { // TODO this is not working as expected
                                sduiLog("Sending to ${it.key} for $name", tag = "ZoneGraph2 > Success > internalZoneMap")
                                send2(success.output, success.input.id.scopes, success.input)
                            }
                        }
                    }
                }
            }
            /**
             * If the request has not been cached, then we will always need to run create() to update the sduiDomain cache
             * And then run update() to update the request cache
             */
            is RequestResult.Failed, is RequestResult.Pending, null -> {
                if (cachedResult is RequestResult.Pending && input is TrivialViewRequest6 && cachedResult.domainIds.containsAll(currentInput.id.scopes)) {
                    sduiLog("RequestResult.Pending $name for $currentInput", tag = "ZoneGraph2 > request")
                    // TODO need a way of combining the request here instead
                    // Issue is a single requestId can spawn multiple different requests to the same zone but with different domainIds
                    return refs
                } else if (cachedResult is RequestResult.Pending) {
                    sduiLog("RequestResult.Pending $name + for $currentInput", tag = "ZoneGraph2 > request")
                    requests[currentInput.requestId] = RequestResult.Pending((cachedResult.domainIds + currentInput.id.scopes).distinct())
                } else {
                    sduiLog("RequestResult.Failed or null $name for $currentInput", tag = "ZoneGraph2 > request")
                    requests[currentInput.requestId] = RequestResult.Pending(currentInput.id.scopes)
                }
                val domainIds = (requests[currentInput.requestId] as? RequestResult.Pending)?.domainIds ?: currentInput.id.scopes // TODO this is probably erroneous also

                if (update == StaticVoid6::class) {
                    sduiLog("StaticVoid6 $name for $currentInput", tag = "ZoneGraph2 > request")
                    domainIds.forEach { domainId ->
                        sduiDomains[domainId] = sduiDomains[domainId] ?: domainId.let {
                            val computingInput = currentInput.toComputingViewRequest6(domainId)
                            val domain = StaticVoid6(computingInput) as D
                            ComputedSduiDomain(
                                domain = domain,
                                sdui = create(domain, computingInput.requestId),
                                domainId = computingInput.focusDomainId
                            ).also {
                                sduiDomains[domainId] = it
                            }
                        }
                    }
                }

                when {
                    domainIds.filterNot { sduiDomains[it] != null && sduiDomains[it] !is PendingSduiDomain }.isEmpty() -> {
                        val sduiDomains = domainIds.mapNotNull { getComputedSubdomain(it) }
                        val updatedDomains = sduiDomains.map {
                            it.copy(
                                sdui = update(
                                    input = currentInput.toComputingViewRequest6(it.domainId),
                                    sduiInput2 = it.sdui,
                                    domain = it.domain,
                                )
                            )
                        }
                        val successDomainIds = sduiDomains.map { it.domainId }
                        val successInput = currentInput

                        val previousInflight = (requests[successInput.requestId] as? Success<D>)?.inflight.orEmpty().toSet()
                        val result = Success(output = updatedDomains, input = successInput, inflight = domainIds)
                        requests[successInput.requestId] = result
                        send2(result.output, successDomainIds - previousInflight, successInput)

                        internalZoneMap.forEach {
                            it.value.requests[successInput.requestId]?.let { requestResult ->
                                (requestResult as? Success<*>)?.let { success ->
                                    if (it.key != name && children.contains(it.key)) { // TODO this is not working as expected
                                        sduiLog("Sending to ${it.key} for $name", tag = "ZoneGraph2 > Domain > internalZoneMap")
                                        send2(success.output, success.input.id.scopes, successInput)
                                    }
                                }
                            }
                        }
                    }

                    else -> {
                        val requestDomains = currentInput.id.scopes.filterNot { sduiDomains.containsKey(it) }
                        requestDomains.forEach { sduiDomains[it] = PendingSduiDomain(it) } // TODO just missing this single line of code made everything go out of control
//                        val domainRequest = requestDomains.map { requestDomain(currentInput, it) } // TODO current rewriting
//                        domainRequest.forEach { publish(it) }
                    }
                }
            }
        }

        return refs
    }

    /**
     * Augment Request will finally send the sduis when the entire list is complete
     */
    fun augmentRequest(input: DomainViewRequest6, domain: DomainEvent6) {
        sduiLog("Augmenting request for $input with ${domain::class}", tag = "ZoneGraph2 > augmentRequest")
        val sdui = create(domain as D, input.requestId)
        val sduiDomain = ComputedSduiDomain(domain, sdui, domain.domainId)
        sduiDomains[domain.domainId] = sduiDomain
        request2(input)
    }

    fun failedDomainRequest(input: DomainViewRequest6, domainId: String) {
        sduiDomains[domainId] = FailedSduiDomain(domainId)
        request2(input)
    }

    fun getComputedSubdomain(domainId: String) = sduiDomains[domainId] as? ComputedSduiDomain<D>

    val sduiDomains = mutableMapOf<String, SduiDomain<D>>()
    val requests = mutableMapOf<String, RequestResult>() // <---- When this is updated
    val subscribedRequests =
        mutableMapOf<String, List<String>>() // <---- This is checked to see if anyone is waiting on that request if computed from scratch

    sealed class SduiDomain<D : ScopedEvent> {
        abstract val domainId: String

        data class PendingSduiDomain<D : ScopedEvent>(
            override val domainId: String,
        ) : SduiDomain<D>()
        data class ComputedSduiDomain<D : ScopedEvent>(
            val domain: D,
            val sdui: SDUIInput2,
            override val domainId: String,
        ) : SduiDomain<D>()

        data class FailedSduiDomain<D : ScopedEvent>(
            override val domainId: String,
        ) : SduiDomain<D>()
    }


    sealed class RequestResult {
        data class Success<D : ScopedEvent>(
            val output: List<ComputedSduiDomain<D>>,
            val input: ViewRequest6,
            val inflight: List<String> = listOf(), // TODO it's a bit jank, but
        ) : RequestResult()

        data class Pending(
            val domainIds: List<String> = listOf(),
        ) : RequestResult()
        data object Failed : RequestResult() // TODO to do at some point
    }

    /**
     * In theory this could be a perfect way to register a streaming interest in requests that update
     * Need sessionDependency send to indicate if sending was successful or not so we can remove from pendingRequests
     */

    companion object {
        inline fun <reified D : DomainEvent6> create(
            name: String,
            crossinline create: (update: D, requestId: String) -> SDUIInput2,
            crossinline update: ((input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D) -> SDUIInput2) = { _, sduiInput2, _ -> sduiInput2 },
            crossinline initiateInput: (input: UninitiatedViewRequest6) -> TrivialViewRequest6 = { input ->
                val id = input.id.name + input.id.scope
                TrivialViewRequest6(
                    id = input.id,
                    ctx = input.ctx,
                    listCtx = input.listCtx,
                    requesterId = input.requesterId,
                    requestId = id,
                )
            },
            crossinline requestDomain: (input: DomainViewRequest6) -> DomainEvent6 = { error("Not implemented requestDomain for $name") },
        ) = object : Zone<D>(D::class) {
            override val name = name
            override fun create(update: D, requestId: String) = create(update, requestId)
            override fun update(input: DomainViewRequest6, sduiInput2: SDUIInput2, domain: D) =
                update(input, sduiInput2, domain)

            override fun requestDomain(input: DomainViewRequest6): DomainEvent6 = requestDomain(input)

            override fun initiateInput(input: UninitiatedViewRequest6) = initiateInput(input)
        }

        lateinit var internalZoneMap: Map<String, Zone<out DomainEvent6>> // TODO make this be the source of truth and not direct state
        var requestTracker = mutableMapOf<String, RequestResult2>()
        sealed class RequestResult2 {
            abstract val rootRequest: ViewRequest6
            data class Failed(
                val requesters: List<String>,
                override val rootRequest: ViewRequest6,
            ) : RequestResult2()

            data class Pending(
                val requesters: Map<String, Set<String>>,
                val output: List<SduiDomain<*>>,
                override val rootRequest: ViewRequest6,
            ) : RequestResult2()

            data class Success(
                override val rootRequest: ViewRequest6,
                val output: List<ComputedSduiDomain<*>>,
            ) : RequestResult2()
        }
    }
}